root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main.exe"
  cmd = "go build -o ./tmp/main.exe main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html", "css"]
  stop_on_error = true

[screen]
  clear_on_rebuild = true